name: 'Zigbee Smoke/CO Detector AllStoNe'
packageKey: 'zigbee-smoke-detector-heiman-as'
description: 'Devices Supported: https://github.com/allstone/Edge-Drivers-Beta/blob/main/zigbee-smoke-co-detector/fingerprints.yml'
permissions:
  zigbee: {}
