name: 'Zigbee Switch Power Mc AllStoNe'
packageKey: 'Zigbee_Switch_Power-v5-as'
description: 'Devices Supported: https://github.com/allstone/Edge-Drivers-Beta/blob/main/zigbee-switch-power-v5/fingerprints.yml'
permissions:
  zigbee: {}
